stop();
var obj = this.attachMovie("shop_mc","shop",100);
obj.mcExtends(ShopMC);
_root.myInventory = new Inventory();
var newCategory = _root.myInventory.addCategory("Gags");
var sub = newCategory.addSubCategory("Drop");
var defaultObj = sub.addObject(new GagObject("Drop","Flower Pot",1,2,0,4,9,"drop","hit_drop"));
defaultObj.addAProp("squashValue",0.8);
var d = sub.addObject(new GagObject("Drop","Sandbag",1,5,0,6,6,"drop","hit_drop"));
d.addAProp("squashValue",0.65);
var d = sub.addObject(new GagObject("Drop","Anvil",1,8,0,8,5,"drop","hit_drop"));
d.addAProp("squashValue",0.4);
var d = sub.addObject(new GagObject("Drop","Safe",1,10,0,10,4,"drop","hit_drop"));
d.addAProp("squashValue",0.25);
var d = sub.addObject(new GagObject("Drop","Piano",1,40,0,15,2,"drop","hit_drop"));
d.addAProp("squashValue",0);
sub.setDefault(defaultObj);
var sub = newCategory.addSubCategory("Squirt");
var defaultObj = sub.addObject(new GagObject("Squirt","Squirting Flower",1,2,0,2,10,"squirt_flower","hit_squirt"));
sub.addObject(new GagObject("Squirt","Glass Of Water",1,4,0,4,8,"squirt_drink","hit_squirt"));
sub.addObject(new GagObject("Squirt","Water Gun",1,6,0,5,6,"squirt_gun","hit_squirt"));
sub.addObject(new GagObject("Squirt","Seltzer Bottle",1,10,0,8,5,"squirt_drink","hit_squirt"));
sub.addObject(new GagObject("Squirt","Water Hose",1,25,0,15,3,"squirt_hose","hit_squirt"));
sub.setDefault(defaultObj);
var sub = newCategory.addSubCategory("Throw");
var defaultObj = sub.addObject(new GagObject("Throw","Tart",1,2,0,2,10,"throw","hit_throw_yellow"));
sub.addObject(new GagObject("Throw","Fruit Pie Slice",1,6,0,4,8,"throw","hit_throw_purple"));
sub.addObject(new GagObject("Throw","Cream Pie Slice",1,10,0,6,6,"throw","hit_throw_yellow"));
sub.addObject(new GagObject("Throw","Fruit Pie",1,25,0,8,4,"throw","hit_throw_purple"));
sub.addObject(new GagObject("Throw","Cream Pie",1,25,0,10,4,"throw","hit_throw_yellow"));
var special = sub.addObject(new GagObject("Throw","Birthday Cake",gVisitedSponsor,50,0,20,2,"throw","hit_throw_yellow"));
sub.setDefault(defaultObj);
var numJellyBeans = 99;
this.shop.init(0,0,_root.myInventory,numJellyBeans);
this.shop.updateJellyBeans();
