if(!_global.MenuManager)
{
   _global.MenuManager.prototype = new MovieClip().init = function(data)
   {
      var _loc1_ = this;
      var _loc2_ = data;
      _loc1_.docWidth_num = _loc2_.docWidth_num;
      _loc1_.docHeight_num = _loc2_.docHeight_num;
      _loc1_.menu_mc = _loc1_;
      if(_loc2_.linkID != null)
      {
         var _loc3_ = _loc1_.menu_mc.attachMovie("generic_mc","menuBG_mc",_loc1_.depths.bg);
         _loc3_.setImage(_loc2_.linkID);
         _loc3_.setPos(_loc1_.docWidth_num / 2,_loc1_.docHeight_num / 2);
      }
      _loc1_.onMakeMenu(_loc2_.menuID_num,_loc2_.menuData);
   };
   _global.MenuManager.prototype = new MovieClip().getMenuData = function(tMenuID, data)
   {
      var _loc1_ = this;
      var _loc2_ = new Object();
      _loc2_.posOffset = new Object();
      _loc2_.item_array = new Array();
      if(tMenuID == _loc1_.menuID.main)
      {
         _loc2_.posOffset.x = 0;
         _loc2_.posOffset.y = 0;
         var _loc3_ = new Object();
         _loc3_.linkID = "illustration_mc";
         _loc3_.alignmentX = "center";
         _loc3_.alignmentY = "center";
         _loc3_.x = _loc1_.docWidth_num * 0.5;
         _loc3_.y = _loc1_.docHeight_num * 0.5 + 40;
         _loc3_.textData = new Object();
         _loc3_.scriptID = "noButton";
         _loc2_.item_array.push(_loc3_);
         _loc3_ = new Object();
         _loc3_.linkID = "swoosh_mc";
         _loc3_.alignmentX = "center";
         _loc3_.alignmentY = "center";
         _loc3_.x = _loc1_.docWidth_num * 0.5 - 10;
         _loc3_.y = _loc1_.docHeight_num * 0.73;
         _loc3_.textData = new Object();
         _loc3_.scriptID = "noButton";
         _loc2_.item_array.push(_loc3_);
         _loc3_ = new Object();
         _loc3_.linkID = "border_mc";
         _loc3_.alignmentX = "center";
         _loc3_.alignmentY = "center";
         _loc3_.x = _loc1_.docWidth_num * 0.5;
         _loc3_.y = _loc1_.docHeight_num * 0.5;
         _loc3_.textData = new Object();
         _loc3_.scriptID = "noButton";
         _loc2_.item_array.push(_loc3_);
         _loc3_ = new Object();
         _loc3_.linkID = "logoSpyro_mc";
         _loc3_.alignmentX = "center";
         _loc3_.alignmentY = "top";
         _loc3_.x = _loc1_.docWidth_num * 0.5;
         _loc3_.y = _loc1_.docHeight_num * 0.01;
         _loc3_.textData = new Object();
         _loc3_.scriptID = "noButton";
         _loc2_.item_array.push(_loc3_);
         _loc3_ = new Object();
         _loc3_.linkID = "btn_playGame_mc";
         _loc3_.alignmentX = "left";
         _loc3_.alignmentY = "center";
         _loc3_.x = _loc1_.docWidth_num * 0.08 + 3;
         _loc3_.y = _loc1_.docHeight_num * 0.73 + 6;
         _loc3_.scriptID = "onNextMenu";
         _loc3_.scriptData = new Object();
         _loc3_.scriptData.nextMenuID = _loc1_.menuID.selectCharacter;
         _loc2_.item_array.push(_loc3_);
         _loc3_ = new Object();
         _loc3_.linkID = "btn_viewInstructions_mc";
         _loc3_.alignmentX = "center";
         _loc3_.alignmentY = "center";
         _loc3_.x = _loc1_.docWidth_num * 0.27;
         _loc3_.y = _loc1_.docHeight_num * 0.73;
         _loc3_.scriptID = "onNextMenu";
         _loc3_.scriptData = new Object();
         _loc3_.scriptData.nextMenuID = _loc1_.menuID.viewInstructions;
         _loc2_.item_array.push(_loc3_);
         _loc3_ = new Object();
         _loc3_.linkID = "btn_VisitWebsite_mc";
         _loc3_.alignmentX = "center";
         _loc3_.alignmentY = "center";
         _loc3_.x = _loc1_.docWidth_num * 0.43 + 3;
         _loc3_.y = _loc1_.docHeight_num * 0.73;
         _loc3_.scriptID = "onGetUrl";
         _loc3_.scriptData = new Object();
         _loc3_.scriptData.url_str = "http://www.neopets.com/process_click.phtml?item_id=4833";
         _loc2_.item_array.push(_loc3_);
         _loc3_ = new Object();
         _loc3_.linkID = "btn_about_mc";
         _loc3_.alignmentX = "center";
         _loc3_.alignmentY = "center";
         _loc3_.x = _loc1_.docWidth_num * 0.56 - 3;
         _loc3_.y = _loc1_.docHeight_num * 0.73;
         _loc3_.scriptID = "onNextMenu";
         _loc3_.scriptData = new Object();
         _loc3_.scriptData.nextMenuID = _loc1_.menuID.about;
         _loc2_.item_array.push(_loc3_);
         _loc3_ = new Object();
         _loc3_.linkID = "btn_trailer_mc";
         _loc3_.alignmentX = "right";
         _loc3_.alignmentY = "center";
         _loc3_.x = _loc1_.docWidth_num * 0.71 + 5;
         _loc3_.y = _loc1_.docHeight_num * 0.73;
         _loc3_.scriptID = "onNextMenu";
         _loc3_.scriptData = new Object();
         _loc3_.scriptData.nextMenuID = _loc1_.menuID.trailer;
         _loc2_.item_array.push(_loc3_);
         _loc3_ = new Object();
         _loc3_.linkID = "btn_newsletter_mc";
         _loc3_.alignmentX = "right";
         _loc3_.alignmentY = "center";
         _loc3_.x = _loc1_.docWidth_num * 0.89;
         _loc3_.y = _loc1_.docHeight_num * 0.73 + 3;
         _loc3_.scriptID = "onGetUrl";
         _loc3_.scriptData = new Object();
         _loc3_.scriptData.url_str = "http://www.neopets.com/process_click.phtml?item_id=4873";
         _loc2_.item_array.push(_loc3_);
         _loc2_.item_array.push(_loc3_);
         _loc3_ = new Object();
         _loc3_.linkID = "logoVUGames_mc";
         _loc3_.alignmentX = "left";
         _loc3_.alignmentY = "bottom";
         _loc3_.x = _loc1_.docWidth_num * 0.03;
         _loc3_.y = _loc1_.docHeight_num * 0.99;
         _loc3_.scriptID = "noButton";
         _loc2_.item_array.push(_loc3_);
         _loc3_ = new Object();
         _loc3_.linkID = "btn_availableNow_mc";
         _loc3_.alignmentX = "center";
         _loc3_.alignmentY = "bottom";
         _loc3_.x = _loc1_.docWidth_num * 0.5;
         _loc3_.y = _loc1_.docHeight_num * 0.99;
         _loc3_.scriptID = "onGetUrl";
         _loc3_.scriptData = new Object();
         _loc3_.scriptData.url_str = "http://www.neopets.com/process_click.phtml?item_id=4833";
         _loc2_.item_array.push(_loc3_);
         _loc3_ = new Object();
         _loc3_.linkID = "legal_mc";
         _loc3_.alignmentX = "right";
         _loc3_.alignmentY = "bottom";
         _loc3_.x = _loc1_.docWidth_num * 0.99;
         _loc3_.y = _loc1_.docHeight_num * 0.99;
         _loc3_.scriptID = "noButton";
         _loc2_.item_array.push(_loc3_);
      }
      else if(tMenuID == _loc1_.menuID.viewInstructions)
      {
         _loc2_.posOffset.x = 0;
         _loc2_.posOffset.y = 0;
         _loc3_ = new Object();
         _loc3_.linkID = "gradientBg_mc";
         _loc3_.alignmentX = "center";
         _loc3_.alignmentY = "center";
         _loc3_.x = _loc1_.docWidth_num * 0.5;
         _loc3_.y = _loc1_.docHeight_num * 0.56;
         _loc3_.textData = new Object();
         _loc3_.scriptID = "noButton";
         _loc2_.item_array.push(_loc3_);
         _loc3_ = new Object();
         _loc3_.linkID = "border_mc";
         _loc3_.alignmentX = "center";
         _loc3_.alignmentY = "center";
         _loc3_.x = _loc1_.docWidth_num * 0.5;
         _loc3_.y = _loc1_.docHeight_num * 0.5;
         _loc3_.textData = new Object();
         _loc3_.scriptID = "noButton";
         _loc2_.item_array.push(_loc3_);
         _loc3_ = new Object();
         _loc3_.linkID = "logoSpyro_mc";
         _loc3_.alignmentX = "center";
         _loc3_.alignmentY = "top";
         _loc3_.x = _loc1_.docWidth_num * 0.5;
         _loc3_.y = _loc1_.docHeight_num * 0.01;
         _loc3_.textData = new Object();
         _loc3_.scriptID = "noButton";
         _loc2_.item_array.push(_loc3_);
         _loc3_ = new Object();
         _loc3_.linkID = "instructionsSCrollPane_mc";
         _loc3_.alignmentX = "center";
         _loc3_.alignmentY = "center";
         _loc3_.x = _loc1_.docWidth_num * 0.5;
         _loc3_.y = _loc1_.docHeight_num * 0.55;
         _loc3_.textData = new Object();
         _loc3_.scriptID = "noButton";
         _loc2_.item_array.push(_loc3_);
         _loc3_ = new Object();
         _loc3_.linkID = "logoVUGames_mc";
         _loc3_.alignmentX = "left";
         _loc3_.alignmentY = "bottom";
         _loc3_.x = _loc1_.docWidth_num * 0.03;
         _loc3_.y = _loc1_.docHeight_num * 0.99;
         _loc3_.scriptID = "noButton";
         _loc2_.item_array.push(_loc3_);
         _loc3_ = new Object();
         _loc3_.linkID = "btn_availableNow_mc";
         _loc3_.alignmentX = "center";
         _loc3_.alignmentY = "bottom";
         _loc3_.x = _loc1_.docWidth_num * 0.5;
         _loc3_.y = _loc1_.docHeight_num * 0.99;
         _loc3_.scriptID = "onGetUrl";
         _loc3_.scriptData = new Object();
         _loc3_.scriptData.url_str = "http://www.neopets.com/process_click.phtml?item_id=4833";
         _loc2_.item_array.push(_loc3_);
         _loc3_ = new Object();
         _loc3_.linkID = "swooshMini_mc";
         _loc3_.alignmentX = "right";
         _loc3_.alignmentY = "bottom";
         _loc3_.x = _loc1_.docWidth_num * 0.935;
         _loc3_.y = _loc1_.docHeight_num * 0.985;
         _loc3_.scriptID = "noButton";
         _loc2_.item_array.push(_loc3_);
         _loc3_ = new Object();
         _loc3_.linkID = "btn_back_mc";
         _loc3_.alignmentX = "right";
         _loc3_.alignmentY = "bottom";
         _loc3_.x = _loc1_.docWidth_num * 0.888;
         _loc3_.y = _loc1_.docHeight_num * 0.92;
         _loc3_.scriptID = "onNextMenu";
         _loc3_.scriptData = new Object();
         _loc3_.scriptData.nextMenuID = _loc1_.menuID.main;
         _loc2_.item_array.push(_loc3_);
      }
      else if(tMenuID == _loc1_.menuID.about)
      {
         _loc2_.posOffset.x = 0;
         _loc2_.posOffset.y = 0;
         _loc3_ = new Object();
         _loc3_.linkID = "gradientBg_mc";
         _loc3_.alignmentX = "center";
         _loc3_.alignmentY = "center";
         _loc3_.x = _loc1_.docWidth_num * 0.5;
         _loc3_.y = _loc1_.docHeight_num * 0.56;
         _loc3_.textData = new Object();
         _loc3_.scriptID = "noButton";
         _loc2_.item_array.push(_loc3_);
         _loc3_ = new Object();
         _loc3_.linkID = "border_mc";
         _loc3_.alignmentX = "center";
         _loc3_.alignmentY = "center";
         _loc3_.x = _loc1_.docWidth_num * 0.5;
         _loc3_.y = _loc1_.docHeight_num * 0.5;
         _loc3_.textData = new Object();
         _loc3_.scriptID = "noButton";
         _loc2_.item_array.push(_loc3_);
         _loc3_ = new Object();
         _loc3_.linkID = "logoSpyro_mc";
         _loc3_.alignmentX = "center";
         _loc3_.alignmentY = "top";
         _loc3_.x = _loc1_.docWidth_num * 0.5;
         _loc3_.y = _loc1_.docHeight_num * 0.01;
         _loc3_.textData = new Object();
         _loc3_.scriptID = "noButton";
         _loc2_.item_array.push(_loc3_);
         _loc3_ = new Object();
         _loc3_.linkID = "aboutSCrollPane_mc";
         _loc3_.alignmentX = "center";
         _loc3_.alignmentY = "center";
         _loc3_.x = _loc1_.docWidth_num * 0.5;
         _loc3_.y = _loc1_.docHeight_num * 0.55;
         _loc3_.textData = new Object();
         _loc3_.scriptID = "noButton";
         _loc2_.item_array.push(_loc3_);
         _loc3_ = new Object();
         _loc3_.linkID = "logoVUGames_mc";
         _loc3_.alignmentX = "left";
         _loc3_.alignmentY = "bottom";
         _loc3_.x = _loc1_.docWidth_num * 0.03;
         _loc3_.y = _loc1_.docHeight_num * 0.99;
         _loc3_.scriptID = "noButton";
         _loc2_.item_array.push(_loc3_);
         _loc3_ = new Object();
         _loc3_.linkID = "btn_availableNow_mc";
         _loc3_.alignmentX = "center";
         _loc3_.alignmentY = "bottom";
         _loc3_.x = _loc1_.docWidth_num * 0.5;
         _loc3_.y = _loc1_.docHeight_num * 0.99;
         _loc3_.scriptID = "onGetUrl";
         _loc3_.scriptData = new Object();
         _loc3_.scriptData.url_str = "http://www.neopets.com/process_click.phtml?item_id=4833";
         _loc2_.item_array.push(_loc3_);
         _loc3_ = new Object();
         _loc3_.linkID = "swooshMini_mc";
         _loc3_.alignmentX = "right";
         _loc3_.alignmentY = "bottom";
         _loc3_.x = _loc1_.docWidth_num * 0.935;
         _loc3_.y = _loc1_.docHeight_num * 0.985;
         _loc3_.scriptID = "noButton";
         _loc2_.item_array.push(_loc3_);
         _loc3_ = new Object();
         _loc3_.linkID = "btn_back_mc";
         _loc3_.alignmentX = "right";
         _loc3_.alignmentY = "bottom";
         _loc3_.x = _loc1_.docWidth_num * 0.888;
         _loc3_.y = _loc1_.docHeight_num * 0.92;
         _loc3_.scriptID = "onNextMenu";
         _loc3_.scriptData = new Object();
         _loc3_.scriptData.nextMenuID = _loc1_.menuID.main;
         _loc2_.item_array.push(_loc3_);
      }
      else if(tMenuID == _loc1_.menuID.trailer)
      {
         _loc2_.posOffset.x = 0;
         _loc2_.posOffset.y = 0;
         _loc3_ = new Object();
         _loc3_.linkID = "gradientBg_mc";
         _loc3_.alignmentX = "center";
         _loc3_.alignmentY = "center";
         _loc3_.x = _loc1_.docWidth_num * 0.5;
         _loc3_.y = _loc1_.docHeight_num * 0.56;
         _loc3_.textData = new Object();
         _loc3_.scriptID = "noButton";
         _loc2_.item_array.push(_loc3_);
         _loc3_ = new Object();
         _loc3_.linkID = "border_mc";
         _loc3_.alignmentX = "center";
         _loc3_.alignmentY = "center";
         _loc3_.x = _loc1_.docWidth_num * 0.5;
         _loc3_.y = _loc1_.docHeight_num * 0.5;
         _loc3_.textData = new Object();
         _loc3_.scriptID = "noButton";
         _loc2_.item_array.push(_loc3_);
         _loc3_ = new Object();
         _loc3_.linkID = "logoSpyro_mc";
         _loc3_.alignmentX = "center";
         _loc3_.alignmentY = "top";
         _loc3_.x = _loc1_.docWidth_num * 0.5;
         _loc3_.y = _loc1_.docHeight_num * 0.01;
         _loc3_.textData = new Object();
         _loc3_.scriptID = "noButton";
         _loc2_.item_array.push(_loc3_);
         _loc3_ = new Object();
         _loc3_.linkID = "viewTrailer_mc";
         _loc3_.alignmentX = "center";
         _loc3_.alignmentY = "center";
         _loc3_.x = _loc1_.docWidth_num * 0.5;
         _loc3_.y = _loc1_.docHeight_num * 0.55;
         _loc3_.textData = new Object();
         _loc3_.scriptID = "noButton";
         _loc2_.item_array.push(_loc3_);
         _loc3_ = new Object();
         _loc3_.linkID = "logoVUGames_mc";
         _loc3_.alignmentX = "left";
         _loc3_.alignmentY = "bottom";
         _loc3_.x = _loc1_.docWidth_num * 0.03;
         _loc3_.y = _loc1_.docHeight_num * 0.99;
         _loc3_.scriptID = "noButton";
         _loc2_.item_array.push(_loc3_);
         _loc3_ = new Object();
         _loc3_.linkID = "btn_availableNow_mc";
         _loc3_.alignmentX = "center";
         _loc3_.alignmentY = "bottom";
         _loc3_.x = _loc1_.docWidth_num * 0.5;
         _loc3_.y = _loc1_.docHeight_num * 0.99;
         _loc3_.scriptID = "onGetUrl";
         _loc3_.scriptData = new Object();
         _loc3_.scriptData.url_str = "http://www.neopets.com/process_click.phtml?item_id=4833";
         _loc2_.item_array.push(_loc3_);
         _loc3_ = new Object();
         _loc3_.linkID = "swooshMini_mc";
         _loc3_.alignmentX = "right";
         _loc3_.alignmentY = "bottom";
         _loc3_.x = _loc1_.docWidth_num * 0.935;
         _loc3_.y = _loc1_.docHeight_num * 0.985;
         _loc3_.scriptID = "noButton";
         _loc2_.item_array.push(_loc3_);
         _loc3_ = new Object();
         _loc3_.linkID = "btn_back_mc";
         _loc3_.alignmentX = "right";
         _loc3_.alignmentY = "bottom";
         _loc3_.x = _loc1_.docWidth_num * 0.888;
         _loc3_.y = _loc1_.docHeight_num * 0.92;
         _loc3_.scriptID = "onNextMenu";
         _loc3_.scriptData = new Object();
         _loc3_.scriptData.nextMenuID = _loc1_.menuID.main;
         _loc2_.item_array.push(_loc3_);
      }
      else if(tMenuID == _loc1_.menuID.selectCharacter)
      {
         _loc2_.posOffset.x = 0;
         _loc2_.posOffset.y = 0;
         _loc3_ = new Object();
         _loc3_.linkID = "gradientBg_mc";
         _loc3_.alignmentX = "center";
         _loc3_.alignmentY = "center";
         _loc3_.x = _loc1_.docWidth_num * 0.5;
         _loc3_.y = _loc1_.docHeight_num * 0.56;
         _loc3_.textData = new Object();
         _loc3_.scriptID = "noButton";
         _loc2_.item_array.push(_loc3_);
         _loc3_ = new Object();
         _loc3_.linkID = "border_mc";
         _loc3_.alignmentX = "center";
         _loc3_.alignmentY = "center";
         _loc3_.x = _loc1_.docWidth_num * 0.5;
         _loc3_.y = _loc1_.docHeight_num * 0.5;
         _loc3_.textData = new Object();
         _loc3_.scriptID = "noButton";
         _loc2_.item_array.push(_loc3_);
         _loc3_ = new Object();
         _loc3_.linkID = "logoSpyro_mc";
         _loc3_.alignmentX = "center";
         _loc3_.alignmentY = "top";
         _loc3_.x = _loc1_.docWidth_num * 0.5;
         _loc3_.y = _loc1_.docHeight_num * 0.01;
         _loc3_.textData = new Object();
         _loc3_.scriptID = "noButton";
         _loc2_.item_array.push(_loc3_);
         _loc3_ = new Object();
         _loc3_.linkID = "spyroMenu_mc";
         _loc3_.alignmentX = "center";
         _loc3_.alignmentY = "center";
         _loc3_.x = 120;
         _loc3_.y = _loc1_.docHeight_num * 0.48;
         _loc3_.textData = new Object();
         _loc3_.scriptID = "onSelectCharacter";
         _loc3_.scriptData = new Object();
         _loc3_.scriptData.characterLinkID = "spyro_mc";
         _loc3_.scriptData.nextMenuID = _loc1_.menuID.selectBG;
         _loc2_.item_array.push(_loc3_);
         _loc3_ = new Object();
         _loc3_.linkID = "btn_playAsSpyro_mc";
         _loc3_.alignmentX = "center";
         _loc3_.alignmentY = "center";
         _loc3_.x = _loc1_.docWidth_num * 0.2;
         _loc3_.y = _loc1_.docHeight_num * 0.7;
         _loc3_.scriptID = "onSelectCharacter";
         _loc3_.scriptData = new Object();
         _loc3_.scriptData.characterLinkID = "spyro_mc";
         _loc3_.scriptData.nextMenuID = _loc1_.menuID.selectBG;
         _loc2_.item_array.push(_loc3_);
         _loc3_ = new Object();
         _loc3_.linkID = "sgtByrdMenu_mc";
         _loc3_.alignmentX = "center";
         _loc3_.alignmentY = "center";
         _loc3_.x = 282;
         _loc3_.y = _loc1_.docHeight_num * 0.48;
         _loc3_.textData = new Object();
         _loc3_.scriptID = "onSelectCharacter";
         _loc3_.scriptData = new Object();
         _loc3_.scriptData.characterLinkID = "sgtByrd_mc";
         _loc3_.scriptData.nextMenuID = _loc1_.menuID.selectBG;
         _loc2_.item_array.push(_loc3_);
         _loc3_ = new Object();
         _loc3_.linkID = "btn_playAsSgtByrd_mc";
         _loc3_.alignmentX = "center";
         _loc3_.alignmentY = "center";
         _loc3_.x = _loc1_.docWidth_num * 0.44;
         _loc3_.y = _loc1_.docHeight_num * 0.7;
         _loc3_.scriptID = "onSelectCharacter";
         _loc3_.scriptData = new Object();
         _loc3_.scriptData.characterLinkID = "sgtByrd_mc";
         _loc3_.scriptData.nextMenuID = _loc1_.menuID.selectBG;
         _loc2_.item_array.push(_loc3_);
         _loc3_ = new Object();
         _loc3_.linkID = "blinkMenu_mc";
         _loc3_.alignmentX = "center";
         _loc3_.alignmentY = "center";
         _loc3_.x = 418;
         _loc3_.y = _loc1_.docHeight_num * 0.47;
         _loc3_.textData = new Object();
         _loc3_.scriptID = "onSelectCharacter";
         _loc3_.scriptData = new Object();
         _loc3_.scriptData.characterLinkID = "blink_mc";
         _loc3_.scriptData.nextMenuID = _loc1_.menuID.selectBG;
         _loc2_.item_array.push(_loc3_);
         _loc3_ = new Object();
         _loc3_.linkID = "btn_playAsBlink_mc";
         _loc3_.alignmentX = "center";
         _loc3_.alignmentY = "center";
         _loc3_.x = _loc1_.docWidth_num * 0.64;
         _loc3_.y = _loc1_.docHeight_num * 0.7;
         _loc3_.scriptID = "onSelectCharacter";
         _loc3_.scriptData = new Object();
         _loc3_.scriptData.characterLinkID = "blink_mc";
         _loc3_.scriptData.nextMenuID = _loc1_.menuID.selectBG;
         _loc2_.item_array.push(_loc3_);
         _loc3_ = new Object();
         _loc3_.linkID = "hunterMenu_mc";
         _loc3_.alignmentX = "center";
         _loc3_.alignmentY = "center";
         _loc3_.x = 520;
         _loc3_.y = _loc1_.docHeight_num * 0.47;
         _loc3_.textData = new Object();
         _loc3_.scriptID = "onSelectCharacter";
         _loc3_.scriptData = new Object();
         _loc3_.scriptData.characterLinkID = "hunter_mc";
         _loc3_.scriptData.nextMenuID = _loc1_.menuID.selectBG;
         _loc2_.item_array.push(_loc3_);
         _loc3_ = new Object();
         _loc3_.linkID = "btn_playAsHunter_mc";
         _loc3_.alignmentX = "center";
         _loc3_.alignmentY = "center";
         _loc3_.x = _loc1_.docWidth_num * 0.82;
         _loc3_.y = _loc1_.docHeight_num * 0.7;
         _loc3_.scriptID = "onSelectCharacter";
         _loc3_.scriptData = new Object();
         _loc3_.scriptData.characterLinkID = "hunter_mc";
         _loc3_.scriptData.nextMenuID = _loc1_.menuID.selectBG;
         _loc2_.item_array.push(_loc3_);
         _loc3_ = new Object();
         _loc3_.linkID = "logoVUGames_mc";
         _loc3_.alignmentX = "left";
         _loc3_.alignmentY = "bottom";
         _loc3_.x = _loc1_.docWidth_num * 0.03;
         _loc3_.y = _loc1_.docHeight_num * 0.99;
         _loc3_.scriptID = "noButton";
         _loc2_.item_array.push(_loc3_);
         _loc3_ = new Object();
         _loc3_.linkID = "btn_availableNow_mc";
         _loc3_.alignmentX = "center";
         _loc3_.alignmentY = "bottom";
         _loc3_.x = _loc1_.docWidth_num * 0.5;
         _loc3_.y = _loc1_.docHeight_num * 0.99;
         _loc3_.scriptID = "onGetUrl";
         _loc3_.scriptData = new Object();
         _loc3_.scriptData.url_str = "http://www.neopets.com/process_click.phtml?item_id=4833";
         _loc2_.item_array.push(_loc3_);
         _loc3_ = new Object();
         _loc3_.linkID = "swooshMini_mc";
         _loc3_.alignmentX = "right";
         _loc3_.alignmentY = "bottom";
         _loc3_.x = _loc1_.docWidth_num * 0.935;
         _loc3_.y = _loc1_.docHeight_num * 0.985;
         _loc3_.scriptID = "noButton";
         _loc2_.item_array.push(_loc3_);
         _loc3_ = new Object();
         _loc3_.linkID = "btn_back_mc";
         _loc3_.alignmentX = "right";
         _loc3_.alignmentY = "bottom";
         _loc3_.x = _loc1_.docWidth_num * 0.888;
         _loc3_.y = _loc1_.docHeight_num * 0.92;
         _loc3_.scriptID = "onNextMenu";
         _loc3_.scriptData = new Object();
         _loc3_.scriptData.nextMenuID = _loc1_.menuID.main;
         _loc2_.item_array.push(_loc3_);
      }
      else if(tMenuID == _loc1_.menuID.selectBG)
      {
         _loc2_.posOffset.x = 0;
         _loc2_.posOffset.y = 0;
         _loc3_ = new Object();
         _loc3_.linkID = "gradientBg_mc";
         _loc3_.alignmentX = "center";
         _loc3_.alignmentY = "center";
         _loc3_.x = _loc1_.docWidth_num * 0.5;
         _loc3_.y = _loc1_.docHeight_num * 0.56;
         _loc3_.textData = new Object();
         _loc3_.scriptID = "noButton";
         _loc2_.item_array.push(_loc3_);
         _loc3_ = new Object();
         _loc3_.linkID = "border_mc";
         _loc3_.alignmentX = "center";
         _loc3_.alignmentY = "center";
         _loc3_.x = _loc1_.docWidth_num * 0.5;
         _loc3_.y = _loc1_.docHeight_num * 0.5;
         _loc3_.textData = new Object();
         _loc3_.scriptID = "noButton";
         _loc2_.item_array.push(_loc3_);
         _loc3_ = new Object();
         _loc3_.linkID = "logoSpyro_mc";
         _loc3_.alignmentX = "center";
         _loc3_.alignmentY = "top";
         _loc3_.x = _loc1_.docWidth_num * 0.5;
         _loc3_.y = _loc1_.docHeight_num * 0.01;
         _loc3_.textData = new Object();
         _loc3_.scriptID = "noButton";
         _loc2_.item_array.push(_loc3_);
         _loc3_ = new Object();
         _loc3_.linkID = "thumbnailBG1_mc";
         _loc3_.alignmentX = "center";
         _loc3_.alignmentY = "center";
         _loc3_.x = _loc1_.docWidth_num * 0.2;
         _loc3_.y = _loc1_.docHeight_num * 0.5;
         _loc3_.textData = new Object();
         _loc3_.scriptID = "onSelectBG";
         _loc3_.scriptData = new Object();
         _loc3_.scriptData.bgLinkID = "backGround1_mc";
         _loc2_.item_array.push(_loc3_);
         _loc3_ = new Object();
         _loc3_.linkID = "btn_playInWorld1_mc";
         _loc3_.alignmentX = "center";
         _loc3_.alignmentY = "center";
         _loc3_.x = _loc1_.docWidth_num * 0.2;
         _loc3_.y = _loc1_.docHeight_num * 0.68;
         _loc3_.scriptID = "onSelectBG";
         _loc3_.scriptData = new Object();
         _loc3_.scriptData.bgLinkID = "backGround1_mc";
         _loc2_.item_array.push(_loc3_);
         _loc3_ = new Object();
         _loc3_.linkID = "thumbnailBG2_mc";
         _loc3_.alignmentX = "center";
         _loc3_.alignmentY = "center";
         _loc3_.x = _loc1_.docWidth_num * 0.4;
         _loc3_.y = _loc1_.docHeight_num * 0.5;
         _loc3_.textData = new Object();
         _loc3_.scriptID = "onSelectBG";
         _loc3_.scriptData = new Object();
         _loc3_.scriptData.bgLinkID = "backGround2_mc";
         _loc2_.item_array.push(_loc3_);
         _loc3_ = new Object();
         _loc3_.linkID = "btn_playInWorld2_mc";
         _loc3_.alignmentX = "center";
         _loc3_.alignmentY = "center";
         _loc3_.x = _loc1_.docWidth_num * 0.4;
         _loc3_.y = _loc1_.docHeight_num * 0.68;
         _loc3_.scriptID = "onSelectBG";
         _loc3_.scriptData = new Object();
         _loc3_.scriptData.bgLinkID = "backGround2_mc";
         _loc2_.item_array.push(_loc3_);
         _loc3_ = new Object();
         _loc3_.linkID = "thumbnailBG3_mc";
         _loc3_.alignmentX = "center";
         _loc3_.alignmentY = "center";
         _loc3_.x = _loc1_.docWidth_num * 0.6;
         _loc3_.y = _loc1_.docHeight_num * 0.5;
         _loc3_.textData = new Object();
         _loc3_.scriptID = "onSelectBG";
         _loc3_.scriptData = new Object();
         _loc3_.scriptData.bgLinkID = "backGround3_mc";
         _loc2_.item_array.push(_loc3_);
         _loc3_ = new Object();
         _loc3_.linkID = "btn_playInWorld3_mc";
         _loc3_.alignmentX = "center";
         _loc3_.alignmentY = "center";
         _loc3_.x = _loc1_.docWidth_num * 0.6;
         _loc3_.y = _loc1_.docHeight_num * 0.68 - 4;
         _loc3_.scriptID = "onSelectBG";
         _loc3_.scriptData = new Object();
         _loc3_.scriptData.bgLinkID = "backGround3_mc";
         _loc2_.item_array.push(_loc3_);
         _loc3_ = new Object();
         _loc3_.linkID = "thumbnailBG4_mc";
         _loc3_.alignmentX = "center";
         _loc3_.alignmentY = "center";
         _loc3_.x = _loc1_.docWidth_num * 0.8;
         _loc3_.y = _loc1_.docHeight_num * 0.5;
         _loc3_.textData = new Object();
         _loc3_.scriptID = "onSelectBG";
         _loc3_.scriptData = new Object();
         _loc3_.scriptData.bgLinkID = "backGround4_mc";
         _loc2_.item_array.push(_loc3_);
         _loc3_ = new Object();
         _loc3_.linkID = "btn_playInWorld4_mc";
         _loc3_.alignmentX = "center";
         _loc3_.alignmentY = "center";
         _loc3_.x = _loc1_.docWidth_num * 0.8;
         _loc3_.y = _loc1_.docHeight_num * 0.68 - 4;
         _loc3_.scriptID = "onSelectBG";
         _loc3_.scriptData = new Object();
         _loc3_.scriptData.bgLinkID = "backGround4_mc";
         _loc2_.item_array.push(_loc3_);
         _loc3_ = new Object();
         _loc3_.linkID = "logoVUGames_mc";
         _loc3_.alignmentX = "left";
         _loc3_.alignmentY = "bottom";
         _loc3_.x = _loc1_.docWidth_num * 0.03;
         _loc3_.y = _loc1_.docHeight_num * 0.99;
         _loc3_.scriptID = "noButton";
         _loc2_.item_array.push(_loc3_);
         _loc3_ = new Object();
         _loc3_.linkID = "btn_availableNow_mc";
         _loc3_.alignmentX = "center";
         _loc3_.alignmentY = "bottom";
         _loc3_.x = _loc1_.docWidth_num * 0.5;
         _loc3_.y = _loc1_.docHeight_num * 0.99;
         _loc3_.scriptID = "onGetUrl";
         _loc3_.scriptData = new Object();
         _loc3_.scriptData.url_str = "http://www.neopets.com/process_click.phtml?item_id=4833";
         _loc2_.item_array.push(_loc3_);
         _loc3_ = new Object();
         _loc3_.linkID = "swooshMini_mc";
         _loc3_.alignmentX = "right";
         _loc3_.alignmentY = "bottom";
         _loc3_.x = _loc1_.docWidth_num * 0.935;
         _loc3_.y = _loc1_.docHeight_num * 0.985;
         _loc3_.scriptID = "noButton";
         _loc2_.item_array.push(_loc3_);
         _loc3_ = new Object();
         _loc3_.linkID = "btn_back_mc";
         _loc3_.alignmentX = "right";
         _loc3_.alignmentY = "bottom";
         _loc3_.x = _loc1_.docWidth_num * 0.888;
         _loc3_.y = _loc1_.docHeight_num * 0.92;
         _loc3_.scriptID = "onNextMenu";
         _loc3_.scriptData = new Object();
         _loc3_.scriptData.nextMenuID = _loc1_.menuID.main;
         _loc2_.item_array.push(_loc3_);
      }
      else if(tMenuID == _loc1_.menuID.gameOver)
      {
         _loc2_.posOffset.x = 0;
         _loc2_.posOffset.y = 0;
         _loc3_ = new Object();
         _loc3_.linkID = "gradientBg_mc";
         _loc3_.alignmentX = "center";
         _loc3_.alignmentY = "center";
         _loc3_.x = _loc1_.docWidth_num * 0.5;
         _loc3_.y = _loc1_.docHeight_num * 0.56;
         _loc3_.textData = new Object();
         _loc3_.scriptID = "noButton";
         _loc2_.item_array.push(_loc3_);
         _loc3_ = new Object();
         _loc3_.linkID = "swoosh_mc";
         _loc3_.alignmentX = "center";
         _loc3_.alignmentY = "center";
         _loc3_.x = _loc1_.docWidth_num * 0.5 - 10;
         _loc3_.y = _loc1_.docHeight_num * 0.73;
         _loc3_.textData = new Object();
         _loc3_.scriptID = "noButton";
         _loc2_.item_array.push(_loc3_);
         _loc3_ = new Object();
         _loc3_.linkID = "border_mc";
         _loc3_.alignmentX = "center";
         _loc3_.alignmentY = "center";
         _loc3_.x = _loc1_.docWidth_num * 0.5;
         _loc3_.y = _loc1_.docHeight_num * 0.5;
         _loc3_.textData = new Object();
         _loc3_.scriptID = "noButton";
         _loc2_.item_array.push(_loc3_);
         _loc3_ = new Object();
         _loc3_.linkID = "logoSpyro_mc";
         _loc3_.alignmentX = "center";
         _loc3_.alignmentY = "top";
         _loc3_.x = _loc1_.docWidth_num * 0.5;
         _loc3_.y = _loc1_.docHeight_num * 0.01;
         _loc3_.textData = new Object();
         _loc3_.scriptID = "noButton";
         _loc2_.item_array.push(_loc3_);
         _loc3_ = new Object();
         _loc3_.linkID = "btn_gameOverScrollText_mc";
         _loc3_.alignmentX = "center";
         _loc3_.alignmentY = "center";
         _loc3_.x = _loc1_.docWidth_num * 0.35;
         _loc3_.y = _loc1_.docHeight_num * 0.46;
         _loc3_.textData = new Object();
         _loc3_.scriptID = "noButton";
         _loc2_.item_array.push(_loc3_);
         _loc3_ = new Object();
         _loc3_.linkID = data.charLinkID_str;
         _loc3_.alignmentX = "left";
         _loc3_.alignmentY = "center";
         _loc3_.x = _loc1_.docWidth_num * 0.62;
         _loc3_.y = _loc1_.docHeight_num * 0.45;
         _loc3_.textData = new Object();
         _loc3_.scriptID = "noButton";
         _loc2_.item_array.push(_loc3_);
         _loc3_ = new Object();
         _loc3_.linkID = "btn_restartGame_mc";
         _loc3_.alignmentX = "left";
         _loc3_.alignmentY = "center";
         _loc3_.x = _loc1_.docWidth_num * 0.16;
         _loc3_.y = _loc1_.docHeight_num * 0.73 + 8;
         _loc3_.scriptID = "onRestartGame";
         _loc3_.scriptData = new Object();
         _loc3_.scriptData;
         _loc2_.item_array.push(_loc3_);
         _loc3_ = new Object();
         _loc3_.linkID = "btn_sendScore_mc";
         _loc3_.alignmentX = "center";
         _loc3_.alignmentY = "center";
         _loc3_.x = _loc1_.docWidth_num * 0.5;
         _loc3_.y = _loc1_.docHeight_num * 0.73 + 3;
         _loc3_.scriptID = "onSendScore";
         _loc3_.scriptData = new Object();
         _loc3_.scriptData.nextMenuID = _loc1_.menuID.main;
         _loc2_.item_array.push(_loc3_);
         _loc3_ = new Object();
         _loc3_.linkID = "btn_visitWebsite_mc";
         _loc3_.alignmentX = "right";
         _loc3_.alignmentY = "center";
         _loc3_.x = _loc1_.docWidth_num * 0.8;
         _loc3_.y = _loc1_.docHeight_num * 0.73;
         _loc3_.scriptID = "onGetUrl";
         _loc3_.scriptData = new Object();
         _loc3_.scriptData.url_str = "http://www.neopets.com/process_click.phtml?item_id=4833";
         _loc2_.item_array.push(_loc3_);
         _loc3_ = new Object();
         _loc3_.linkID = "logoVUGames_mc";
         _loc3_.alignmentX = "left";
         _loc3_.alignmentY = "bottom";
         _loc3_.x = _loc1_.docWidth_num * 0.03;
         _loc3_.y = _loc1_.docHeight_num * 0.99;
         _loc3_.scriptID = "noButton";
         _loc2_.item_array.push(_loc3_);
         _loc3_ = new Object();
         _loc3_.linkID = "btn_availableNow_mc";
         _loc3_.alignmentX = "center";
         _loc3_.alignmentY = "bottom";
         _loc3_.x = _loc1_.docWidth_num * 0.5;
         _loc3_.y = _loc1_.docHeight_num * 0.99;
         _loc3_.scriptID = "onGetUrl";
         _loc3_.scriptData = new Object();
         _loc3_.scriptData.url_str = "http://www.neopets.com/process_click.phtml?item_id=4833";
         _loc2_.item_array.push(_loc3_);
         _loc3_ = new Object();
         _loc3_.linkID = "legal_mc";
         _loc3_.alignmentX = "right";
         _loc3_.alignmentY = "bottom";
         _loc3_.x = _loc1_.docWidth_num * 0.99;
         _loc3_.y = _loc1_.docHeight_num * 0.99;
         _loc3_.scriptID = "noButton";
         _loc2_.item_array.push(_loc3_);
      }
      else if(tMenuID == _loc1_.menuID.selectPowerup)
      {
         _loc2_.posOffset.x = 0;
         _loc2_.posOffset.y = -75;
         _loc3_ = new Object();
         _loc3_.linkID = "selectPowerupBg_mc";
         _loc3_.alignmentX = "center";
         _loc3_.alignmentY = "center";
         _loc3_.x = _loc1_.docWidth_num * 0.5;
         _loc3_.y = _loc1_.docHeight_num * 0.5;
         _loc3_.textData = new Object();
         _loc3_.scriptID = "noButton";
         _loc2_.item_array.push(_loc3_);
         _loc3_ = new Object();
         _loc3_.classID = "toggleButton_mc";
         _loc3_.linkID = "btn_powerup1_mc";
         _loc3_.alignmentX = "center";
         _loc3_.alignmentY = "center";
         _loc3_.x = _loc1_.docWidth_num * 0.4;
         _loc3_.y = _loc1_.docHeight_num * 0.4;
         _loc3_.scriptID = "onSelectPowerup";
         _loc3_.scriptData = new Object();
         _loc3_.scriptData = 1;
         _loc3_.info_str = "Big Shot: doubles the projectile size";
         _loc3_.activated = true;
         _loc2_.item_array.push(_loc3_);
         _loc3_ = new Object();
         _loc3_.classID = "toggleButton_mc";
         _loc3_.linkID = "btn_powerup2_mc";
         _loc3_.alignmentX = "center";
         _loc3_.alignmentY = "center";
         _loc3_.x = _loc1_.docWidth_num * 0.5;
         _loc3_.y = _loc1_.docHeight_num * 0.4;
         _loc3_.scriptID = "onSelectPowerup";
         _loc3_.scriptData = new Object();
         _loc3_.scriptData = 2;
         _loc3_.info_str = "Tri-Shot: splits the projectile into 3 parts";
         _loc3_.activated = true;
         _loc2_.item_array.push(_loc3_);
         _loc3_ = new Object();
         _loc3_.classID = "toggleButton_mc";
         _loc3_.linkID = "btn_powerup3_mc";
         _loc3_.alignmentX = "center";
         _loc3_.alignmentY = "center";
         _loc3_.x = _loc1_.docWidth_num * 0.6;
         _loc3_.y = _loc1_.docHeight_num * 0.4;
         _loc3_.scriptID = "onSelectPowerup";
         _loc3_.scriptData = new Object();
         _loc3_.scriptData = 3;
         _loc3_.info_str = "Magna Shot: navigates projectile towards the target";
         _loc3_.activated = true;
         _loc2_.item_array.push(_loc3_);
      }
      return _loc2_;
   };
   _global.MenuManager.prototype = new MovieClip().onMakeMenu = function(menuID_num, externalMenuData)
   {
      var _loc3_ = this.getMenuData(menuID_num,externalMenuData);
      var _loc1_ = _loc3_.item_array.length;
      while(true)
      {
         _loc1_;
         if(_loc1_--)
         {
            if(_loc3_.item_array[_loc1_].classID != null)
            {
               var classID = _loc3_.item_array[_loc1_].classID;
            }
            else
            {
               var classID = "button_mc";
            }
            var _loc2_ = this.menu_mc.attachMovie(classID,_loc3_.item_array[_loc1_].mc + "" + (this.depths.menu + (menuID_num * 10 + _loc1_)),this.depths.menu + (menuID_num * 10 + _loc1_));
            _loc2_.init(_loc3_.item_array[_loc1_]);
            _loc2_.setPosBy(_loc3_.posOffset);
            _loc2_.addListener(this);
            this.addListener(_loc2_);
            continue;
         }
         break;
      }
   };
   _global.MenuManager.prototype = new MovieClip().onRemoveMenu = function()
   {
      this.broadcastMessage("onRemoveButton");
   };
   _global.MenuManager.prototype = new MovieClip().onNextMenu = function(data)
   {
      this.onRemoveMenu();
      this.onMakeMenu(data.nextMenuID);
   };
   _global.MenuManager.prototype = new MovieClip().onGetURL = function(data)
   {
   };
   _global.MenuManager.prototype = new MovieClip().onSelectCharacter = function(data)
   {
      this.broadcastMessage("onSetCharacter",data.characterLinkID);
      this.onNextMenu(data);
   };
   _global.MenuManager.prototype = new MovieClip().onSelectBG = function(data)
   {
      var _loc1_ = this;
      _loc1_.broadcastMessage("onSetBG",data.bgLinkID);
      _loc1_.onRemoveMenu();
      _loc1_.broadcastMessage("onGameStart");
   };
   _global.MenuManager.prototype = new MovieClip().onSelectPowerup = function(data)
   {
      this.broadcastMessage("onActivatePowerupBtn",data);
      this.onRemoveMenu();
   };
   _global.MenuManager.prototype = new MovieClip().onShowInfo = function(data)
   {
      this.broadcastMessage("onShowInfo",data);
   };
   _global.MenuManager.prototype = new MovieClip().onHideInfo = function(data)
   {
      this.broadcastMessage("onHideInfo",data);
   };
   _global.MenuManager.prototype = new MovieClip().onContinue = function(data)
   {
      this.onRemoveMenu();
      this.broadcastMessage("onContinue");
   };
   _global.MenuManager.prototype = new MovieClip().onRestartGame = function(data)
   {
      this.onRemoveMenu();
      this.broadcastMessage("onRestartGame");
   };
   _global.MenuManager.prototype = new MovieClip().onSendScore = function(data)
   {
      this.onRemoveMenu();
      this.broadcastMessage("onSendScore");
   };
   _global.MenuManager.prototype = new MovieClip().depths = new Object();
   _global.MenuManager.prototype = new MovieClip().menuID = new Object();
   §§push(ASSetPropFlags(_global.MenuManager.prototype,null,1));
}
§§pop();
